# Generated by Django 6.0.6 on 2026-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
