# Generated by Codex on 2026-08-05

from django.db import migrations, models


def activate_existing_users(apps, schema_editor):
    User = apps.get_model("user", "User")
    User.objects.filter(is_active=False).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_is_active_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(activate_existing_users, migrations.RunPython.noop),
    ]
